### ISSUE TITLE
[eOS 8.0 daily build 20240217] Verified this extension works on the Early Access Elementary OS 8.0 builds

### ISSUE THREAD

**Issue by truefakts** [lenemter/wingpanel-indicator-namarupa#2]
No issue to report here. I tested this extension on the Early Access build of Elementary OS 8.0, using the latest release of the .deb. It works without issue, and runs on startup. The applications I tested are:

- [Mostly Works ] Nextcloud Desktop client flatpak. The icon does not properly render, the user sees the ? symbol. But that is likely because the application's icon is missing in from the Elementary OS icon set, as opposed to an issue with this extension
- [Works ] Steam flatpak. The icon appears without issue, fully functional too
- [Broken] Discord. No icon appears. However this is likely a discord issue and not something to worry about.

Thank you for developing this extension! This will be something I install immediately when eOS 8.0 is released

**Comment by WebShapedBiz** [comment]
I'm sorry to report that it does not work with the the eOS final release, tested with classic and secure sessions. The three-dotted menu is just not visible.

**Comment by TheKamboy** [comment]
@truefakts

**Comment by codecowboy** [comment]
@WebShapedBiz  Can you elaborate? When I rebooted, the dots were there (in an x11 session) but the tray is empty @lenemter

**Comment by MagicMusicLive** [comment]
Unfortunately, @codecowboy, I tried everything I could find online, and I cannot track my many steps back to this issue. However, here is the issue that helped me finally get it working: https://github.com/MvBonin/wingpanel-community-indicators/issues/15, albeit with only a small number of apps.

**Comment by WebShapedBiz** [comment]
Unfortunately, @codecowboy, I tried everything I could find online, and I cannot track my many steps back to this issue. However, here is the issue that helped me finally get it working: https://github.com/MvBonin/wingpanel-community-indicators/issues/15, albeit with only a small number of apps.

**Comment by codecowboy** [comment]
@WebShapedBiz can you give me an example of an app that works? I installed Discord and nothing shows up in the tray. I tried all the suggestions at that link  and nothing has worked.

**Comment by MagicMusicLive** [comment]
You can test it @codecowboy with the pCloud and CopyQ (I tried the flatpack version). CopyQ shows a no-icon icon, but the menu works. Unfortunately, the clipboard functionality of CopyQ doesn't; it is a Wayland thing.
From what I can recall, Discord, Slack, Gmail-Desktop, and many others stopped working around Electron version 25-27. Apparently, some underlying libraries from this Ayatana thingy haven't been updated for a decade, so apps with newer versions of Electron won't work.

My two cents: The sooner this distro dies, the sooner those guys can move on to something more useful.

**Comment by WebShapedBiz** [comment]
You can test it @codecowboy with the pCloud and CopyQ (I tried the flatpack version). CopyQ shows a no-icon icon, but the menu works. Unfortunately, the clipboard functionality of CopyQ doesn't; it is a Wayland thing.
From what I can recall, Discord, Slack, Gmail-Desktop, and many others stopped working around Electron version 25-27. Apparently, some underlying libraries from this Ayatana thingy haven't been updated for a decade, so apps with newer versions of Electron won't work.

My two cents: The sooner this distro dies, the sooner those guys can move on to something more useful. No minimize, no working clipboard (they removed it from Plank), no tray icons, all this you can find in, let's say, upcoming pop_os Cosmic Epoch and many other distros. I've been using eOS exclusively since 2012. and those guys have been fighting users from day one. They were in luck since then there were not many good alternatives. Nowadays, almost every distro is better than eOS. The aforementioned pop_os Cosmic Epoch is written in Rust, and it's insanely fast and good-looking and has everything eOS users have to beg for.

**Comment by codecowboy** [comment]
Yep. I agree. They seem to have an obtuse and opinionated view on some UX things I fundamentally disagree with ( and so do most of the users) and they have no interest in changing them. It was refreshing when I last used it (Hera I think) but v8 is full of bugs. Pantheon-tweaks used to solve a lot of my gripes but now has fewer features. It also wouldn't work in X11 without going down a flatpak permissions rabbit-hole. The whole thing has been endlessly frustrating and the tray icons are the final straw. I'll be switching to PopOS today. I just want a second machine for AI stuff and eOS just doesn't cut it anymore.
